server:
  port: 10000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/jpa
    name: jpa
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update # update mode ( create, create-drop, validate )
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # camel -> underscore , mapping name default
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy # logical naming same as upper

# Search hikari, tomcat, dbcp datasource
# hibernate properties
# After -> persistence.yml
# persistence-unit?